### ISSUE TITLE
MNE version?

### ISSUE THREAD

**Issue by snapfinger** [UMCU-RIBS/ieeg-fmri-dataset-quickstart#1]
Hi there, thanks for sharing this dataset and code. I wonder what is the version of your MNE? I had the following error when running the last block of the `visualize_coverage` code (I downloaded the jupyter notebook as .py file). I think this errror is probably because of the different MNE versions because this seems to work fine in your example even when there's no such input parameter `trans` ? 

```
Setting channel info structure...
visualize_coverage.py:118: RuntimeWarning: Fiducial point nasion not found, assuming identity unknown to head transformation
  raw.set_montage(montage)
Traceback (most recent call last):
  File "visualize_coverage.py", line 134, in <module>
    fig = mne.viz.plot_alignment(raw.info,
  File "<decorator-gen-173>", line 12, in plot_alignment
  File "/hd2/sw1/anaconda3/envs/dipy/lib/python3.8/site-packages/mne/viz/_3d.py", line 604, in plot_alignment
    raise ValueError(msg % 'sensors')
ValueError: A head<->mri transformation matrix (trans) is required to plot sensors in mri coordinates, `trans=None` is not allowed
```

**Comment by Immiora** [comment]
Thanks for your comment! Indeed, here is the version I used for making the visualization script:

`mne.__version__`
`'0.22.0'`

I will take a look at the newer version in the coming days and try to update the script accordingly.

Thank you again for bringing this to my attention!

**Comment by snapfinger** [comment]
Thanks, can you also provide the version of your mne_bids package? After downgrading to 0.22.0 mne, my current mne_bids does not seem to be compatible with it

**Comment by Immiora** [comment]
Hi,

`mne_bids:         0.10`.

I seem to be having issues with the new mne version on our system. I opened an issue [here](https://github.com/mne-tools/mne-python/issues/10890). Cannot look at the trans issues until I get it to work.

But intuitively from the description, I think the identity trans should work, since the transformation is already done externally:

```
identity_trans = mne.transforms.Transform('head', 'mri')
# mne.viz.set_3d_options(antialias=False)
fig = mne.viz.plot_alignment(raw.info, trans=identity_trans,
               subject='sub-' + subject,
               subjects_dir=os.path.dirname(fs_dir),
               surfaces=['pial'],
               coord_frame='mri')
mne.viz.set_3d_view(fig, 180, 70, distance=.5)
```

Have not tested this of course since I cannot seem to produce plots with the new version. But the should be the logic of it, I think.

Ideally, the ras-transformation should just happen within the plot_alignment (now done externally), but I need to figure out the right file to point to in trans. Much of MNE is tailored to EEG/MEG, and it is not always easy for me to adapt to iEEG data.

**Comment by snapfinger** [comment]
Cool, thanks, the identity transformation works well (below). 

There are some package conflicts on my machine (ubuntu 18.04) that I cannot use mne_bids 0.10 with mne 0.22 (will throw `ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
mne-bids 0.10 requires mne>=0.24, but you have mne 0.22.0 which is incompatible.`). But I can use identity transformation with mne 1.0.3 and mne-bids 0.10 to visualize without problem.


![vis](https://user-images.githubusercontent.com/13393457/176938741-93a24781-156f-43ce-8a49-5af541c3650d.png)

**Comment by Immiora** [comment]
Excellent, great this worked :)
